[project]
name = "excel-to-markdown"
version = "0.1.0"
description = "Convert Excel files to Markdown format"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.0.0",
    "openpyxl>=3.0.0",
    "tabulate>=0.9.0",
    "markitdown[xlsx]>=0.1.0",
]
